file = open("file.txt", "w")
#file.write("Hello welcome to Parul university.")
#file.write(" I'm from Vadodara. ")
f = input("Enter Details : ")
file.write(f)
file.close()
file = open("file.txt", "r")
print(file.read())
